# Generated by Django 4.2.7 on 2024-01-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='doctor', max_length=100),
        ),
    ]
